[build]
publish = "public"
command = "make build"

[context.production.environment]
  HUGO_VERSION = "0.124.1"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.124.1"
